name: docker-image-cd

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: saucydorito/gossett-ceg3120
          tags: |
            type=ref,event=tag,format={{version}}
            type=ref,event=tag,format={{major}}
            type=ref,event=tag,format={{major}}.{{minor}}
            type=raw,value=latest

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./project5/angular-site
          file:    ./project5/angular-site/Dockerfile
          push:    true
          tags:    ${{ steps.meta.outputs.tags }}
