name: docker-image-ci

on:
  push:
    branches: [main]
    workflow-dispatch:
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: ceg3120-cicd-Saucy-tgossett/project4/angular-site
          file: ceg3120-cicd-Saucy-tgossett/project4/angular-site/Dockerfile
          push: true
          tags: saucydorito/gossett-ceg3120-angular-site:latest

